[project]
name = "buzzr"
dynamic = ["version"]
description = "FRC match clipper."
readme = "README.md"
authors = [{ name = "Jeffrey Morris", email = "jeff@jeff-m.com" }]
requires-python = ">=3.14"
dependencies = ["pyqt6>=6.11.0"]

[project.scripts]
buzzr = "buzzr.main:main"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[dependency-groups]
dev = ["pyright>=1.1.414", "ruff>=0.16.9"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pyright]
typeCheckingMode = "basic"
include = ["src"]
